package com.tareqdubaee.localpdftools;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.provider.Settings;import android.webkit.*;import androidx.annotation.Nullable;import java.util.*;

public class MainActivity extends Activity {
  WebView web; ValueCallback<Uri[]> fileCallback; static final int PICK=10;
  @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(false);s.setMediaPlaybackRequiresUserGesture(false);WebView.setWebContentsDebuggingEnabled(false);web.setWebViewClient(new WebViewClient());web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;try{startActivityForResult(p.createIntent(),PICK);}catch(Exception e){fileCallback=null;return false;}return true;}});web.setDownloadListener((url,ua,cd,mime,len)->{if(url.startsWith("blob:")){web.evaluateJavascript("(async()=>{const r=await fetch('"+url+"');const b=await r.blob();const a=await b.arrayBuffer();let s='';const u=new Uint8Array(a);for(let i=0;i<u.length;i+=32768)s+=String.fromCharCode(...u.subarray(i,i+32768));AndroidSave.save(btoa(s),'"+escapeJs(URLUtil.guessFileName(url,cd,mime))+"');})()",null);}});web.addJavascriptInterface(new Object(){@JavascriptInterface public void save(String b64,String name){byte[] data=android.util.Base64.decode(b64,android.util.Base64.DEFAULT);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,name);pending=data;startActivityForResult(i,11);}},"AndroidSave");web.loadUrl("file:///android_asset/www/index.html");}
  byte[] pending;
  static String escapeJs(String s){return s.replace("\\","\\\\").replace("'","\\'");}
  @Override protected void onActivityResult(int req,int res,@Nullable Intent data){super.onActivityResult(req,res,data);if(req==PICK){if(fileCallback!=null){fileCallback.onReceiveValue(res==RESULT_OK?WebChromeClient.FileChooserParams.parseResult(res,data):null);fileCallback=null;}}else if(req==11&&res==RESULT_OK&&data!=null&&pending!=null){try(java.io.OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write(pending);}catch(Exception ignored){}pending=null;}}
  @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
